
# This file is automatically generated, you probably don't want to edit this

bayesmetasmdOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bayesmetasmdOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            n1i = NULL,
            m1i = NULL,
            sd1i = NULL,
            n2i = NULL,
            m2i = NULL,
            sd2i = NULL,
            slab = NULL,
            cormeasure = "SMD",
            tauPrior = "uniform",
            scalePrior = 10,
            muPrior = "uniform",
            muMeanPrior = 0.5,
            muStandardDeviationPrior = 0.2, ...) {

            super$initialize(
                package='MAJOR',
                name='bayesmetasmd',
                requiresData=TRUE,
                ...)

            private$..n1i <- jmvcore::OptionVariable$new(
                "n1i",
                n1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m1i <- jmvcore::OptionVariable$new(
                "m1i",
                m1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd1i <- jmvcore::OptionVariable$new(
                "sd1i",
                sd1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..n2i <- jmvcore::OptionVariable$new(
                "n2i",
                n2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m2i <- jmvcore::OptionVariable$new(
                "m2i",
                m2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd2i <- jmvcore::OptionVariable$new(
                "sd2i",
                sd2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab,
                suggested=list(
                    "nominal"))
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "MD",
                    "SMD",
                    "SMDH",
                    "ROM"),
                default="SMD")
            private$..tauPrior <- jmvcore::OptionList$new(
                "tauPrior",
                tauPrior,
                options=list(
                    "halfCauchy",
                    "halfNormal",
                    "uniform",
                    "sqrt",
                    "normal",
                    "Jeffreys",
                    "conventional",
                    "DuMouchel",
                    "shrinkage",
                    "I2"),
                default="uniform")
            private$..scalePrior <- jmvcore::OptionNumber$new(
                "scalePrior",
                scalePrior,
                min=0.01,
                max=100,
                default=10)
            private$..muPrior <- jmvcore::OptionList$new(
                "muPrior",
                muPrior,
                options=list(
                    "uniform",
                    "normal"),
                default="uniform")
            private$..muMeanPrior <- jmvcore::OptionNumber$new(
                "muMeanPrior",
                muMeanPrior,
                min=0.01,
                max=100,
                default=0.5)
            private$..muStandardDeviationPrior <- jmvcore::OptionNumber$new(
                "muStandardDeviationPrior",
                muStandardDeviationPrior,
                min=0.01,
                max=100,
                default=0.2)

            self$.addOption(private$..n1i)
            self$.addOption(private$..m1i)
            self$.addOption(private$..sd1i)
            self$.addOption(private$..n2i)
            self$.addOption(private$..m2i)
            self$.addOption(private$..sd2i)
            self$.addOption(private$..slab)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..tauPrior)
            self$.addOption(private$..scalePrior)
            self$.addOption(private$..muPrior)
            self$.addOption(private$..muMeanPrior)
            self$.addOption(private$..muStandardDeviationPrior)
        }),
    active = list(
        n1i = function() private$..n1i$value,
        m1i = function() private$..m1i$value,
        sd1i = function() private$..sd1i$value,
        n2i = function() private$..n2i$value,
        m2i = function() private$..m2i$value,
        sd2i = function() private$..sd2i$value,
        slab = function() private$..slab$value,
        cormeasure = function() private$..cormeasure$value,
        tauPrior = function() private$..tauPrior$value,
        scalePrior = function() private$..scalePrior$value,
        muPrior = function() private$..muPrior$value,
        muMeanPrior = function() private$..muMeanPrior$value,
        muStandardDeviationPrior = function() private$..muStandardDeviationPrior$value),
    private = list(
        ..n1i = NA,
        ..m1i = NA,
        ..sd1i = NA,
        ..n2i = NA,
        ..m2i = NA,
        ..sd2i = NA,
        ..slab = NA,
        ..cormeasure = NA,
        ..tauPrior = NA,
        ..scalePrior = NA,
        ..muPrior = NA,
        ..muMeanPrior = NA,
        ..muStandardDeviationPrior = NA)
)

bayesmetasmdResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$.items[["textRICH"]],
        plot = function() private$.items[["plot"]],
        plotPDTau = function() private$.items[["plotPDTau"]],
        plotPDMu = function() private$.items[["plotPDMu"]],
        plotJPD = function() private$.items[["plotJPD"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mean Differences")
            self$add(jmvcore::Table$new(
                options=options,
                name="textRICH",
                title="Random-Effects Model - Posterior Summary",
                refs=list(
                    "bayesmeta"),
                rows=6,
                columns=list(
                    list(
                        `name`="Labels", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Tau", 
                        `type`="number"),
                    list(
                        `name`="Mu", 
                        `type`="number"),
                    list(
                        `name`="Theta", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=900,
                height=600,
                renderFun=".plot",
                refs=list(
                    "bayesmeta")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotPDTau",
                title="Marginal Posterior Density Plots (\u03C4)",
                width=900,
                height=600,
                renderFun=".plotPDTau",
                refs=list(
                    "bayesmeta")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotPDMu",
                title="Marginal Posterior Density Plots (\u03BC)",
                width=900,
                height=600,
                renderFun=".plotPDMu",
                refs=list(
                    "bayesmeta")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotJPD",
                title="Joint Posterior Density of Heterogeneity (\u03C4) and Effect (\u03BC)",
                width=900,
                height=600,
                renderFun=".plotJPD",
                refs=list(
                    "bayesmeta")))}))

bayesmetasmdBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bayesmetasmdBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'bayesmetasmd',
                version = c(1,0,0),
                options = options,
                results = bayesmetasmdResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mean Differences
#'
#' 
#' @param data .
#' @param n1i .
#' @param m1i .
#' @param sd1i .
#' @param n2i .
#' @param m2i .
#' @param sd2i .
#' @param slab .
#' @param cormeasure .
#' @param tauPrior .
#' @param scalePrior .
#' @param muPrior .
#' @param muMeanPrior .
#' @param muStandardDeviationPrior .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotPDTau} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotPDMu} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotJPD} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
bayesmetasmd <- function(
    data,
    n1i,
    m1i,
    sd1i,
    n2i,
    m2i,
    sd2i,
    slab,
    cormeasure = "SMD",
    tauPrior = "uniform",
    scalePrior = 10,
    muPrior = "uniform",
    muMeanPrior = 0.5,
    muStandardDeviationPrior = 0.2) {

    if ( ! requireNamespace('jmvcore'))
        stop('bayesmetasmd requires jmvcore to be installed (restart may be required)')

    if ( ! missing(n1i)) n1i <- jmvcore::resolveQuo(jmvcore::enquo(n1i))
    if ( ! missing(m1i)) m1i <- jmvcore::resolveQuo(jmvcore::enquo(m1i))
    if ( ! missing(sd1i)) sd1i <- jmvcore::resolveQuo(jmvcore::enquo(sd1i))
    if ( ! missing(n2i)) n2i <- jmvcore::resolveQuo(jmvcore::enquo(n2i))
    if ( ! missing(m2i)) m2i <- jmvcore::resolveQuo(jmvcore::enquo(m2i))
    if ( ! missing(sd2i)) sd2i <- jmvcore::resolveQuo(jmvcore::enquo(sd2i))
    if ( ! missing(slab)) slab <- jmvcore::resolveQuo(jmvcore::enquo(slab))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(n1i), n1i, NULL),
            `if`( ! missing(m1i), m1i, NULL),
            `if`( ! missing(sd1i), sd1i, NULL),
            `if`( ! missing(n2i), n2i, NULL),
            `if`( ! missing(m2i), m2i, NULL),
            `if`( ! missing(sd2i), sd2i, NULL),
            `if`( ! missing(slab), slab, NULL))


    options <- bayesmetasmdOptions$new(
        n1i = n1i,
        m1i = m1i,
        sd1i = sd1i,
        n2i = n2i,
        m2i = m2i,
        sd2i = sd2i,
        slab = slab,
        cormeasure = cormeasure,
        tauPrior = tauPrior,
        scalePrior = scalePrior,
        muPrior = muPrior,
        muMeanPrior = muMeanPrior,
        muStandardDeviationPrior = muStandardDeviationPrior)

    analysis <- bayesmetasmdClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
