
# This file is automatically generated, you probably don't want to edit this

bayesmetacorrOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bayesmetacorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rcor = NULL,
            samplesize = NULL,
            slab = NULL,
            cormeasure = "ZCOR",
            tauPrior = "uniform",
            scalePrior = 10,
            muPrior = "uniform",
            muMeanPrior = 0.5,
            muStandardDeviationPrior = 0.2, ...) {

            super$initialize(
                package='MAJOR',
                name='bayesmetacorr',
                requiresData=TRUE,
                ...)

            private$..rcor <- jmvcore::OptionVariable$new(
                "rcor",
                rcor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..samplesize <- jmvcore::OptionVariable$new(
                "samplesize",
                samplesize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab,
                suggested=list(
                    "nominaltext"))
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "COR",
                    "UCOR",
                    "ZCOR"),
                default="ZCOR")
            private$..tauPrior <- jmvcore::OptionList$new(
                "tauPrior",
                tauPrior,
                options=list(
                    "halfCauchy",
                    "halfNormal",
                    "uniform",
                    "sqrt",
                    "normal",
                    "Jeffreys",
                    "conventional",
                    "DuMouchel",
                    "shrinkage",
                    "I2"),
                default="uniform")
            private$..scalePrior <- jmvcore::OptionNumber$new(
                "scalePrior",
                scalePrior,
                min=0.01,
                max=100,
                default=10)
            private$..muPrior <- jmvcore::OptionList$new(
                "muPrior",
                muPrior,
                options=list(
                    "uniform",
                    "normal"),
                default="uniform")
            private$..muMeanPrior <- jmvcore::OptionNumber$new(
                "muMeanPrior",
                muMeanPrior,
                min=0.01,
                max=100,
                default=0.5)
            private$..muStandardDeviationPrior <- jmvcore::OptionNumber$new(
                "muStandardDeviationPrior",
                muStandardDeviationPrior,
                min=0.01,
                max=100,
                default=0.2)

            self$.addOption(private$..rcor)
            self$.addOption(private$..samplesize)
            self$.addOption(private$..slab)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..tauPrior)
            self$.addOption(private$..scalePrior)
            self$.addOption(private$..muPrior)
            self$.addOption(private$..muMeanPrior)
            self$.addOption(private$..muStandardDeviationPrior)
        }),
    active = list(
        rcor = function() private$..rcor$value,
        samplesize = function() private$..samplesize$value,
        slab = function() private$..slab$value,
        cormeasure = function() private$..cormeasure$value,
        tauPrior = function() private$..tauPrior$value,
        scalePrior = function() private$..scalePrior$value,
        muPrior = function() private$..muPrior$value,
        muMeanPrior = function() private$..muMeanPrior$value,
        muStandardDeviationPrior = function() private$..muStandardDeviationPrior$value),
    private = list(
        ..rcor = NA,
        ..samplesize = NA,
        ..slab = NA,
        ..cormeasure = NA,
        ..tauPrior = NA,
        ..scalePrior = NA,
        ..muPrior = NA,
        ..muMeanPrior = NA,
        ..muStandardDeviationPrior = NA)
)

bayesmetacorrResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$.items[["textRICH"]],
        plot = function() private$.items[["plot"]],
        plotPDTau = function() private$.items[["plotPDTau"]],
        plotPDMu = function() private$.items[["plotPDMu"]],
        plotJPD = function() private$.items[["plotJPD"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation Coefficients")
            self$add(jmvcore::Table$new(
                options=options,
                name="textRICH",
                title="Random-Effects Model - Posterior Summary",
                rows=6,
                columns=list(
                    list(
                        `name`="Labels", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Tau", 
                        `type`="number"),
                    list(
                        `name`="Mu", 
                        `type`="number"),
                    list(
                        `name`="Theta", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=900,
                height=600,
                renderFun=".plot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotPDTau",
                title="Marginal Posterior Density Plots (\u03C4)",
                width=900,
                height=600,
                renderFun=".plotPDTau"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotPDMu",
                title="Marginal Posterior Density Plots (\u03BC)",
                width=900,
                height=600,
                renderFun=".plotPDMu"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotJPD",
                title="Joint Posterior Density of Heterogeneity (\u03C4) and Effect (\u03BC)",
                width=900,
                height=600,
                renderFun=".plotJPD"))}))

bayesmetacorrBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bayesmetacorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'bayesmetacorr',
                version = c(1,0,2),
                options = options,
                results = bayesmetacorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Correlation Coefficients
#'
#' 
#' @param data .
#' @param rcor .
#' @param samplesize .
#' @param slab .
#' @param cormeasure .
#' @param tauPrior .
#' @param scalePrior .
#' @param muPrior .
#' @param muMeanPrior .
#' @param muStandardDeviationPrior .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotPDTau} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotPDMu} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotJPD} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
bayesmetacorr <- function(
    data,
    rcor,
    samplesize,
    slab,
    cormeasure = "ZCOR",
    tauPrior = "uniform",
    scalePrior = 10,
    muPrior = "uniform",
    muMeanPrior = 0.5,
    muStandardDeviationPrior = 0.2) {

    if ( ! requireNamespace('jmvcore'))
        stop('bayesmetacorr requires jmvcore to be installed (restart may be required)')

    options <- bayesmetacorrOptions$new(
        rcor = rcor,
        samplesize = samplesize,
        slab = slab,
        cormeasure = cormeasure,
        tauPrior = tauPrior,
        scalePrior = scalePrior,
        muPrior = muPrior,
        muMeanPrior = muMeanPrior,
        muStandardDeviationPrior = muStandardDeviationPrior)

    results <- bayesmetacorrResults$new(
        options = options)

    analysis <- bayesmetacorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
