
# This file is automatically generated, you probably don't want to edit this

bayesmetacorrOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bayesmetacorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rcor = NULL,
            samplesize = NULL,
            slab = NULL,
            cormeasure = "ZCOR",
            level = 95,
            showModelFit = FALSE,
            addcred = FALSE,
            addfit = TRUE,
            showweights = FALSE,
            steps = 5,
            xAxisTitle = NULL,
            pchForest = "15",
            forestOrder = "fit", ...) {

            super$initialize(
                package='MAJOR',
                name='bayesmetacorr',
                requiresData=TRUE,
                ...)

            private$..rcor <- jmvcore::OptionVariable$new(
                "rcor",
                rcor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..samplesize <- jmvcore::OptionVariable$new(
                "samplesize",
                samplesize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab,
                suggested=list(
                    "nominaltext"))
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "COR",
                    "UCOR",
                    "ZCOR"),
                default="ZCOR")
            private$..level <- jmvcore::OptionNumber$new(
                "level",
                level,
                min=50,
                max=99.9,
                default=95)
            private$..showModelFit <- jmvcore::OptionBool$new(
                "showModelFit",
                showModelFit,
                default=FALSE)
            private$..addcred <- jmvcore::OptionBool$new(
                "addcred",
                addcred,
                default=FALSE)
            private$..addfit <- jmvcore::OptionBool$new(
                "addfit",
                addfit,
                default=TRUE)
            private$..showweights <- jmvcore::OptionBool$new(
                "showweights",
                showweights,
                default=FALSE)
            private$..steps <- jmvcore::OptionNumber$new(
                "steps",
                steps,
                min=1,
                max=999,
                default=5)
            private$..xAxisTitle <- jmvcore::OptionString$new(
                "xAxisTitle",
                xAxisTitle)
            private$..pchForest <- jmvcore::OptionList$new(
                "pchForest",
                pchForest,
                options=list(
                    "16",
                    "18",
                    "15",
                    "17",
                    "1",
                    "5",
                    "0",
                    "2",
                    "8"),
                default="15")
            private$..forestOrder <- jmvcore::OptionList$new(
                "forestOrder",
                forestOrder,
                options=list(
                    "obs",
                    "fit",
                    "prec",
                    "resid",
                    "abs.resid"),
                default="fit")

            self$.addOption(private$..rcor)
            self$.addOption(private$..samplesize)
            self$.addOption(private$..slab)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..level)
            self$.addOption(private$..showModelFit)
            self$.addOption(private$..addcred)
            self$.addOption(private$..addfit)
            self$.addOption(private$..showweights)
            self$.addOption(private$..steps)
            self$.addOption(private$..xAxisTitle)
            self$.addOption(private$..pchForest)
            self$.addOption(private$..forestOrder)
        }),
    active = list(
        rcor = function() private$..rcor$value,
        samplesize = function() private$..samplesize$value,
        slab = function() private$..slab$value,
        cormeasure = function() private$..cormeasure$value,
        level = function() private$..level$value,
        showModelFit = function() private$..showModelFit$value,
        addcred = function() private$..addcred$value,
        addfit = function() private$..addfit$value,
        showweights = function() private$..showweights$value,
        steps = function() private$..steps$value,
        xAxisTitle = function() private$..xAxisTitle$value,
        pchForest = function() private$..pchForest$value,
        forestOrder = function() private$..forestOrder$value),
    private = list(
        ..rcor = NA,
        ..samplesize = NA,
        ..slab = NA,
        ..cormeasure = NA,
        ..level = NA,
        ..showModelFit = NA,
        ..addcred = NA,
        ..addfit = NA,
        ..showweights = NA,
        ..steps = NA,
        ..xAxisTitle = NA,
        ..pchForest = NA,
        ..forestOrder = NA)
)

bayesmetacorrResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$.items[["textRICH"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation Coefficients")
            self$add(jmvcore::Table$new(
                options=options,
                name="textRICH",
                title="Random-Effects Model - Posterior Summary",
                rows=6,
                columns=list(
                    list(
                        `name`="Labels", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Tau", 
                        `type`="number"),
                    list(
                        `name`="Mu", 
                        `type`="number"),
                    list(
                        `name`="Theta", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot"))}))

bayesmetacorrBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bayesmetacorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'bayesmetacorr',
                version = c(1,0,2),
                options = options,
                results = bayesmetacorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Correlation Coefficients
#'
#' 
#' @param data .
#' @param rcor .
#' @param samplesize .
#' @param slab .
#' @param cormeasure .
#' @param level .
#' @param showModelFit .
#' @param addcred .
#' @param addfit .
#' @param showweights .
#' @param steps .
#' @param xAxisTitle .
#' @param pchForest .
#' @param forestOrder .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
bayesmetacorr <- function(
    data,
    rcor,
    samplesize,
    slab,
    cormeasure = "ZCOR",
    level = 95,
    showModelFit = FALSE,
    addcred = FALSE,
    addfit = TRUE,
    showweights = FALSE,
    steps = 5,
    xAxisTitle,
    pchForest = "15",
    forestOrder = "fit") {

    if ( ! requireNamespace('jmvcore'))
        stop('bayesmetacorr requires jmvcore to be installed (restart may be required)')

    options <- bayesmetacorrOptions$new(
        rcor = rcor,
        samplesize = samplesize,
        slab = slab,
        cormeasure = cormeasure,
        level = level,
        showModelFit = showModelFit,
        addcred = addcred,
        addfit = addfit,
        showweights = showweights,
        steps = steps,
        xAxisTitle = xAxisTitle,
        pchForest = pchForest,
        forestOrder = forestOrder)

    results <- bayesmetacorrResults$new(
        options = options)

    analysis <- bayesmetacorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
