
# This file is automatically generated, you probably don't want to edit this

changeScoreOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "changeScoreOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            n1i_pre = NULL,
            m1i_pre = NULL,
            sd1i_pre = NULL,
            m1i_post = NULL,
            sd1i_post = NULL,
            n2i_pre = NULL,
            m2i_pre = NULL,
            sd2i_pre = NULL,
            m2i_post = NULL,
            sd2i_post = NULL,
            ri = NULL,
            slab = NULL,
            methodmetacor = "FE",
            cormeasure = "SMCR",
            fsntype = "Rosenthal",
            testType = FALSE, ...) {

            super$initialize(
                package='MAJOR',
                name='changeScore',
                requiresData=TRUE,
                ...)

            private$..n1i_pre <- jmvcore::OptionVariable$new(
                "n1i_pre",
                n1i_pre,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m1i_pre <- jmvcore::OptionVariable$new(
                "m1i_pre",
                m1i_pre,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd1i_pre <- jmvcore::OptionVariable$new(
                "sd1i_pre",
                sd1i_pre,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m1i_post <- jmvcore::OptionVariable$new(
                "m1i_post",
                m1i_post,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd1i_post <- jmvcore::OptionVariable$new(
                "sd1i_post",
                sd1i_post,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..n2i_pre <- jmvcore::OptionVariable$new(
                "n2i_pre",
                n2i_pre,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m2i_pre <- jmvcore::OptionVariable$new(
                "m2i_pre",
                m2i_pre,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd2i_pre <- jmvcore::OptionVariable$new(
                "sd2i_pre",
                sd2i_pre,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m2i_post <- jmvcore::OptionVariable$new(
                "m2i_post",
                m2i_post,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd2i_post <- jmvcore::OptionVariable$new(
                "sd2i_post",
                sd2i_post,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ri <- jmvcore::OptionVariable$new(
                "ri",
                ri,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab,
                suggested=list(
                    "nominal"))
            private$..methodmetacor <- jmvcore::OptionList$new(
                "methodmetacor",
                methodmetacor,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "PM",
                    "FE"),
                default="FE")
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "MC",
                    "SMCC",
                    "SMCR"),
                default="SMCR")
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
            private$..testType <- jmvcore::OptionBool$new(
                "testType",
                testType,
                default=FALSE)

            self$.addOption(private$..n1i_pre)
            self$.addOption(private$..m1i_pre)
            self$.addOption(private$..sd1i_pre)
            self$.addOption(private$..m1i_post)
            self$.addOption(private$..sd1i_post)
            self$.addOption(private$..n2i_pre)
            self$.addOption(private$..m2i_pre)
            self$.addOption(private$..sd2i_pre)
            self$.addOption(private$..m2i_post)
            self$.addOption(private$..sd2i_post)
            self$.addOption(private$..ri)
            self$.addOption(private$..slab)
            self$.addOption(private$..methodmetacor)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..fsntype)
            self$.addOption(private$..testType)
        }),
    active = list(
        n1i_pre = function() private$..n1i_pre$value,
        m1i_pre = function() private$..m1i_pre$value,
        sd1i_pre = function() private$..sd1i_pre$value,
        m1i_post = function() private$..m1i_post$value,
        sd1i_post = function() private$..sd1i_post$value,
        n2i_pre = function() private$..n2i_pre$value,
        m2i_pre = function() private$..m2i_pre$value,
        sd2i_pre = function() private$..sd2i_pre$value,
        m2i_post = function() private$..m2i_post$value,
        sd2i_post = function() private$..sd2i_post$value,
        ri = function() private$..ri$value,
        slab = function() private$..slab$value,
        methodmetacor = function() private$..methodmetacor$value,
        cormeasure = function() private$..cormeasure$value,
        fsntype = function() private$..fsntype$value,
        testType = function() private$..testType$value),
    private = list(
        ..n1i_pre = NA,
        ..m1i_pre = NA,
        ..sd1i_pre = NA,
        ..m1i_post = NA,
        ..sd1i_post = NA,
        ..n2i_pre = NA,
        ..m2i_pre = NA,
        ..sd2i_pre = NA,
        ..m2i_post = NA,
        ..sd2i_post = NA,
        ..ri = NA,
        ..slab = NA,
        ..methodmetacor = NA,
        ..cormeasure = NA,
        ..fsntype = NA,
        ..testType = NA)
)

changeScoreResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$.items[["textRICH"]],
        tableTauSqaured = function() private$.items[["tableTauSqaured"]],
        fsnRICH = function() private$.items[["fsnRICH"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Change Score")
            self$add(jmvcore::Table$new(
                options=options,
                name="textRICH",
                refs=list(
                    "metafor"),
                title="Random-Effects Model",
                rows=2,
                columns=list(
                    list(
                        `name`="Intercept", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `type`="number"),
                    list(
                        `name`="Z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="CILow", 
                        `title`="CI Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="CIHigh", 
                        `title`="CI Upper Bound", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableTauSqaured",
                title="Heterogeneity Statistics",
                rows=1,
                columns=list(
                    list(
                        `name`="tauSQRT", 
                        `title`="Tau", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="tauSqComb", 
                        `title`="Tau\u00B2", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ISqu", 
                        `title`="I\u00B2", 
                        `type`="text"),
                    list(
                        `name`="HSqu", 
                        `title`="H\u00B2", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="RSqu", 
                        `title`="R\u00B2", 
                        `type`="text"),
                    list(
                        `name`="QallDF", 
                        `title`="df", 
                        `type`="integer", 
                        `format`="zto"),
                    list(
                        `name`="Qall", 
                        `title`="Q", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="QallPval", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fsnRICH",
                title="",
                rows=4,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Test Name", 
                        `type`="text"),
                    list(
                        `name`="failSafeNumber", 
                        `title`="value", 
                        `type`="integer", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

changeScoreBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "changeScoreBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'changeScore',
                version = c(1,0,0),
                options = options,
                results = changeScoreResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Change Score
#'
#' 
#' @param data .
#' @param n1i_pre .
#' @param m1i_pre .
#' @param sd1i_pre .
#' @param m1i_post .
#' @param sd1i_post .
#' @param n2i_pre .
#' @param m2i_pre .
#' @param sd2i_pre .
#' @param m2i_post .
#' @param sd2i_post .
#' @param ri .
#' @param slab .
#' @param methodmetacor .
#' @param cormeasure .
#' @param fsntype .
#' @param testType .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableTauSqaured} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fsnRICH} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
changeScore <- function(
    data,
    n1i_pre,
    m1i_pre,
    sd1i_pre,
    m1i_post,
    sd1i_post,
    n2i_pre,
    m2i_pre,
    sd2i_pre,
    m2i_post,
    sd2i_post,
    ri,
    slab,
    methodmetacor = "FE",
    cormeasure = "SMCR",
    fsntype = "Rosenthal",
    testType = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('changeScore requires jmvcore to be installed (restart may be required)')

    if ( ! missing(n1i_pre)) n1i_pre <- jmvcore::resolveQuo(jmvcore::enquo(n1i_pre))
    if ( ! missing(m1i_pre)) m1i_pre <- jmvcore::resolveQuo(jmvcore::enquo(m1i_pre))
    if ( ! missing(sd1i_pre)) sd1i_pre <- jmvcore::resolveQuo(jmvcore::enquo(sd1i_pre))
    if ( ! missing(m1i_post)) m1i_post <- jmvcore::resolveQuo(jmvcore::enquo(m1i_post))
    if ( ! missing(sd1i_post)) sd1i_post <- jmvcore::resolveQuo(jmvcore::enquo(sd1i_post))
    if ( ! missing(n2i_pre)) n2i_pre <- jmvcore::resolveQuo(jmvcore::enquo(n2i_pre))
    if ( ! missing(m2i_pre)) m2i_pre <- jmvcore::resolveQuo(jmvcore::enquo(m2i_pre))
    if ( ! missing(sd2i_pre)) sd2i_pre <- jmvcore::resolveQuo(jmvcore::enquo(sd2i_pre))
    if ( ! missing(m2i_post)) m2i_post <- jmvcore::resolveQuo(jmvcore::enquo(m2i_post))
    if ( ! missing(sd2i_post)) sd2i_post <- jmvcore::resolveQuo(jmvcore::enquo(sd2i_post))
    if ( ! missing(ri)) ri <- jmvcore::resolveQuo(jmvcore::enquo(ri))
    if ( ! missing(slab)) slab <- jmvcore::resolveQuo(jmvcore::enquo(slab))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(n1i_pre), n1i_pre, NULL),
            `if`( ! missing(m1i_pre), m1i_pre, NULL),
            `if`( ! missing(sd1i_pre), sd1i_pre, NULL),
            `if`( ! missing(m1i_post), m1i_post, NULL),
            `if`( ! missing(sd1i_post), sd1i_post, NULL),
            `if`( ! missing(n2i_pre), n2i_pre, NULL),
            `if`( ! missing(m2i_pre), m2i_pre, NULL),
            `if`( ! missing(sd2i_pre), sd2i_pre, NULL),
            `if`( ! missing(m2i_post), m2i_post, NULL),
            `if`( ! missing(sd2i_post), sd2i_post, NULL),
            `if`( ! missing(ri), ri, NULL),
            `if`( ! missing(slab), slab, NULL))


    options <- changeScoreOptions$new(
        n1i_pre = n1i_pre,
        m1i_pre = m1i_pre,
        sd1i_pre = sd1i_pre,
        m1i_post = m1i_post,
        sd1i_post = sd1i_post,
        n2i_pre = n2i_pre,
        m2i_pre = m2i_pre,
        sd2i_pre = sd2i_pre,
        m2i_post = m2i_post,
        sd2i_post = sd2i_post,
        ri = ri,
        slab = slab,
        methodmetacor = methodmetacor,
        cormeasure = cormeasure,
        fsntype = fsntype,
        testType = testType)

    analysis <- changeScoreClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
