
# This file is automatically generated, you probably don't want to edit this

metaMeanDiffOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "metaMeanDiffOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            n1i = NULL,
            m1i = NULL,
            sd1i = NULL,
            n2i = NULL,
            m2i = NULL,
            sd2i = NULL,
            slab = NULL,
            moderatorcor = NULL,
            methodmetacor = "REML",
            cormeasure = "SMD",
            moderatorType = "NON",
            testType = FALSE,
            level = 95,
            showModelFit = FALSE,
            addcred = FALSE,
            addfit = TRUE,
            showweights = FALSE,
            steps = 5,
            xAxisTitle = NULL,
            forestPlotSize = "SMALL",
            funnelPlotSize = "SMALL",
            pchForest = "15",
            forestOrder = "fit",
            fsntype = "Rosenthal",
            tesAlternative = "two.sided",
            tesAlpha = 0.5,
            tesH0 = 0,
            showTes = FALSE,
            puniformSide = "right",
            selModelType = "beta",
            yaxis = "sei",
            yaxisInv = FALSE,
            enhanceFunnel = FALSE,
            lowerTOST = -0.5,
            upperTOST = 0.5,
            alphaTOST = 0.05,
            showTOST = FALSE,
            showInfPlot = FALSE,
            showLL = FALSE,
            showPuniform = FALSE,
            showSelmodel = FALSE, ...) {

            super$initialize(
                package='MAJOR',
                name='metaMeanDiff',
                requiresData=TRUE,
                ...)

            private$..n1i <- jmvcore::OptionVariable$new(
                "n1i",
                n1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m1i <- jmvcore::OptionVariable$new(
                "m1i",
                m1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd1i <- jmvcore::OptionVariable$new(
                "sd1i",
                sd1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..n2i <- jmvcore::OptionVariable$new(
                "n2i",
                n2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m2i <- jmvcore::OptionVariable$new(
                "m2i",
                m2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd2i <- jmvcore::OptionVariable$new(
                "sd2i",
                sd2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab,
                suggested=list(
                    "nominal"))
            private$..moderatorcor <- jmvcore::OptionVariable$new(
                "moderatorcor",
                moderatorcor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..methodmetacor <- jmvcore::OptionList$new(
                "methodmetacor",
                methodmetacor,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "PM",
                    "FE"),
                default="REML")
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "MD",
                    "SMD",
                    "SMDH",
                    "ROM"),
                default="SMD")
            private$..moderatorType <- jmvcore::OptionList$new(
                "moderatorType",
                moderatorType,
                options=list(
                    "NON",
                    "CAT",
                    "CON"),
                default="NON")
            private$..testType <- jmvcore::OptionBool$new(
                "testType",
                testType,
                default=FALSE)
            private$..level <- jmvcore::OptionNumber$new(
                "level",
                level,
                min=50,
                max=99.9,
                default=95)
            private$..showModelFit <- jmvcore::OptionBool$new(
                "showModelFit",
                showModelFit,
                default=FALSE)
            private$..addcred <- jmvcore::OptionBool$new(
                "addcred",
                addcred,
                default=FALSE)
            private$..addfit <- jmvcore::OptionBool$new(
                "addfit",
                addfit,
                default=TRUE)
            private$..showweights <- jmvcore::OptionBool$new(
                "showweights",
                showweights,
                default=FALSE)
            private$..steps <- jmvcore::OptionNumber$new(
                "steps",
                steps,
                min=1,
                max=999,
                default=5)
            private$..xAxisTitle <- jmvcore::OptionString$new(
                "xAxisTitle",
                xAxisTitle)
            private$..forestPlotSize <- jmvcore::OptionList$new(
                "forestPlotSize",
                forestPlotSize,
                options=list(
                    "SMALL",
                    "MEDIUM",
                    "LARGE",
                    "SMALLWIDE",
                    "MEDIUMWIDE",
                    "LARGEWIDE"),
                default="SMALL")
            private$..funnelPlotSize <- jmvcore::OptionList$new(
                "funnelPlotSize",
                funnelPlotSize,
                options=list(
                    "SMALL",
                    "MEDIUM",
                    "LARGE"),
                default="SMALL")
            private$..pchForest <- jmvcore::OptionList$new(
                "pchForest",
                pchForest,
                options=list(
                    "16",
                    "18",
                    "15",
                    "17",
                    "1",
                    "5",
                    "0",
                    "2",
                    "8"),
                default="15")
            private$..forestOrder <- jmvcore::OptionList$new(
                "forestOrder",
                forestOrder,
                options=list(
                    "obs",
                    "fit",
                    "prec",
                    "resid",
                    "abs.resid"),
                default="fit")
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
            private$..tesAlternative <- jmvcore::OptionList$new(
                "tesAlternative",
                tesAlternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..tesAlpha <- jmvcore::OptionNumber$new(
                "tesAlpha",
                tesAlpha,
                min=0.000001,
                max=1,
                default=0.5)
            private$..tesH0 <- jmvcore::OptionNumber$new(
                "tesH0",
                tesH0,
                min=-9999,
                max=9999,
                default=0)
            private$..showTes <- jmvcore::OptionBool$new(
                "showTes",
                showTes,
                default=FALSE)
            private$..puniformSide <- jmvcore::OptionList$new(
                "puniformSide",
                puniformSide,
                options=list(
                    "right",
                    "left"),
                default="right")
            private$..selModelType <- jmvcore::OptionList$new(
                "selModelType",
                selModelType,
                options=list(
                    "beta",
                    "halfnorm",
                    "negexp",
                    "logistic",
                    "power",
                    "stepfun"),
                default="beta")
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "sei",
                    "vi",
                    "ni",
                    "sqrtni",
                    "lni"),
                default="sei")
            private$..yaxisInv <- jmvcore::OptionBool$new(
                "yaxisInv",
                yaxisInv,
                default=FALSE)
            private$..enhanceFunnel <- jmvcore::OptionBool$new(
                "enhanceFunnel",
                enhanceFunnel,
                default=FALSE)
            private$..lowerTOST <- jmvcore::OptionNumber$new(
                "lowerTOST",
                lowerTOST,
                min=-100,
                max=100,
                default=-0.5)
            private$..upperTOST <- jmvcore::OptionNumber$new(
                "upperTOST",
                upperTOST,
                min=-100,
                max=100,
                default=0.5)
            private$..alphaTOST <- jmvcore::OptionNumber$new(
                "alphaTOST",
                alphaTOST,
                min=0.000001,
                max=1,
                default=0.05)
            private$..showTOST <- jmvcore::OptionBool$new(
                "showTOST",
                showTOST,
                default=FALSE)
            private$..showInfPlot <- jmvcore::OptionBool$new(
                "showInfPlot",
                showInfPlot,
                default=FALSE)
            private$..showLL <- jmvcore::OptionBool$new(
                "showLL",
                showLL,
                default=FALSE)
            private$..showPuniform <- jmvcore::OptionBool$new(
                "showPuniform",
                showPuniform,
                default=FALSE)
            private$..showSelmodel <- jmvcore::OptionBool$new(
                "showSelmodel",
                showSelmodel,
                default=FALSE)

            self$.addOption(private$..n1i)
            self$.addOption(private$..m1i)
            self$.addOption(private$..sd1i)
            self$.addOption(private$..n2i)
            self$.addOption(private$..m2i)
            self$.addOption(private$..sd2i)
            self$.addOption(private$..slab)
            self$.addOption(private$..moderatorcor)
            self$.addOption(private$..methodmetacor)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..moderatorType)
            self$.addOption(private$..testType)
            self$.addOption(private$..level)
            self$.addOption(private$..showModelFit)
            self$.addOption(private$..addcred)
            self$.addOption(private$..addfit)
            self$.addOption(private$..showweights)
            self$.addOption(private$..steps)
            self$.addOption(private$..xAxisTitle)
            self$.addOption(private$..forestPlotSize)
            self$.addOption(private$..funnelPlotSize)
            self$.addOption(private$..pchForest)
            self$.addOption(private$..forestOrder)
            self$.addOption(private$..fsntype)
            self$.addOption(private$..tesAlternative)
            self$.addOption(private$..tesAlpha)
            self$.addOption(private$..tesH0)
            self$.addOption(private$..showTes)
            self$.addOption(private$..puniformSide)
            self$.addOption(private$..selModelType)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..yaxisInv)
            self$.addOption(private$..enhanceFunnel)
            self$.addOption(private$..lowerTOST)
            self$.addOption(private$..upperTOST)
            self$.addOption(private$..alphaTOST)
            self$.addOption(private$..showTOST)
            self$.addOption(private$..showInfPlot)
            self$.addOption(private$..showLL)
            self$.addOption(private$..showPuniform)
            self$.addOption(private$..showSelmodel)
        }),
    active = list(
        n1i = function() private$..n1i$value,
        m1i = function() private$..m1i$value,
        sd1i = function() private$..sd1i$value,
        n2i = function() private$..n2i$value,
        m2i = function() private$..m2i$value,
        sd2i = function() private$..sd2i$value,
        slab = function() private$..slab$value,
        moderatorcor = function() private$..moderatorcor$value,
        methodmetacor = function() private$..methodmetacor$value,
        cormeasure = function() private$..cormeasure$value,
        moderatorType = function() private$..moderatorType$value,
        testType = function() private$..testType$value,
        level = function() private$..level$value,
        showModelFit = function() private$..showModelFit$value,
        addcred = function() private$..addcred$value,
        addfit = function() private$..addfit$value,
        showweights = function() private$..showweights$value,
        steps = function() private$..steps$value,
        xAxisTitle = function() private$..xAxisTitle$value,
        forestPlotSize = function() private$..forestPlotSize$value,
        funnelPlotSize = function() private$..funnelPlotSize$value,
        pchForest = function() private$..pchForest$value,
        forestOrder = function() private$..forestOrder$value,
        fsntype = function() private$..fsntype$value,
        tesAlternative = function() private$..tesAlternative$value,
        tesAlpha = function() private$..tesAlpha$value,
        tesH0 = function() private$..tesH0$value,
        showTes = function() private$..showTes$value,
        puniformSide = function() private$..puniformSide$value,
        selModelType = function() private$..selModelType$value,
        yaxis = function() private$..yaxis$value,
        yaxisInv = function() private$..yaxisInv$value,
        enhanceFunnel = function() private$..enhanceFunnel$value,
        lowerTOST = function() private$..lowerTOST$value,
        upperTOST = function() private$..upperTOST$value,
        alphaTOST = function() private$..alphaTOST$value,
        showTOST = function() private$..showTOST$value,
        showInfPlot = function() private$..showInfPlot$value,
        showLL = function() private$..showLL$value,
        showPuniform = function() private$..showPuniform$value,
        showSelmodel = function() private$..showSelmodel$value),
    private = list(
        ..n1i = NA,
        ..m1i = NA,
        ..sd1i = NA,
        ..n2i = NA,
        ..m2i = NA,
        ..sd2i = NA,
        ..slab = NA,
        ..moderatorcor = NA,
        ..methodmetacor = NA,
        ..cormeasure = NA,
        ..moderatorType = NA,
        ..testType = NA,
        ..level = NA,
        ..showModelFit = NA,
        ..addcred = NA,
        ..addfit = NA,
        ..showweights = NA,
        ..steps = NA,
        ..xAxisTitle = NA,
        ..forestPlotSize = NA,
        ..funnelPlotSize = NA,
        ..pchForest = NA,
        ..forestOrder = NA,
        ..fsntype = NA,
        ..tesAlternative = NA,
        ..tesAlpha = NA,
        ..tesH0 = NA,
        ..showTes = NA,
        ..puniformSide = NA,
        ..selModelType = NA,
        ..yaxis = NA,
        ..yaxisInv = NA,
        ..enhanceFunnel = NA,
        ..lowerTOST = NA,
        ..upperTOST = NA,
        ..alphaTOST = NA,
        ..showTOST = NA,
        ..showInfPlot = NA,
        ..showLL = NA,
        ..showPuniform = NA,
        ..showSelmodel = NA)
)

metaMeanDiffResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$.items[["textRICH"]],
        tableTauSqaured = function() private$.items[["tableTauSqaured"]],
        modelFitRICH = function() private$.items[["modelFitRICH"]],
        summaryOutputText = function() private$.items[["summaryOutputText"]],
        summaryOutputText2 = function() private$.items[["summaryOutputText2"]],
        plot = function() private$.items[["plot"]],
        plotMed = function() private$.items[["plotMed"]],
        plotLarge = function() private$.items[["plotLarge"]],
        plotSmallWide = function() private$.items[["plotSmallWide"]],
        plotMedWide = function() private$.items[["plotMedWide"]],
        plotLargeWide = function() private$.items[["plotLargeWide"]],
        selModelOutput = function() private$.items[["selModelOutput"]],
        fsnRICH = function() private$.items[["fsnRICH"]],
        funplot = function() private$.items[["funplot"]],
        funplotMed = function() private$.items[["funplotMed"]],
        funplotLarge = function() private$.items[["funplotLarge"]],
        resultsTES = function() private$.items[["resultsTES"]],
        resultsTES2 = function() private$.items[["resultsTES2"]],
        tesOutput3 = function() private$.items[["tesOutput3"]],
        puniformModelOutput = function() private$.items[["puniformModelOutput"]],
        puniformModelOutput2 = function() private$.items[["puniformModelOutput2"]],
        TOSToutput = function() private$.items[["TOSToutput"]],
        TOSToutputtext = function() private$.items[["TOSToutputtext"]],
        tostplot = function() private$.items[["tostplot"]],
        likelihoodPlot = function() private$.items[["likelihoodPlot"]],
        diagPlotAll = function() private$.items[["diagPlotAll"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="textRICH",
                refs=list(
                    "metafor"),
                title="Random-Effects Model",
                rows=2,
                columns=list(
                    list(
                        `name`="Intercept", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `type`="number"),
                    list(
                        `name`="Z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="CILow", 
                        `title`="CI Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="CIHigh", 
                        `title`="CI Upper Bound", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableTauSqaured",
                title="Heterogeneity Statistics",
                rows=1,
                columns=list(
                    list(
                        `name`="tauSQRT", 
                        `title`="Tau", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="tauSqComb", 
                        `title`="Tau\u00B2", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ISqu", 
                        `title`="I\u00B2", 
                        `type`="text"),
                    list(
                        `name`="HSqu", 
                        `title`="H\u00B2", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="RSqu", 
                        `title`="R\u00B2", 
                        `type`="text"),
                    list(
                        `name`="QallDF", 
                        `title`="df", 
                        `type`="integer", 
                        `format`="zto"),
                    list(
                        `name`="Qall", 
                        `title`="Q", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="QallPval", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelFitRICH",
                title="Model Fit Statistics and Information Criteria",
                rows=2,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="loglikelihood", 
                        `title`="log-likelihood", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="deviance", 
                        `title`="Deviance", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="AIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="BIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="AICc", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="summaryOutputText",
                title="Model Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="summaryOutputText2",
                title="Model Summary"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotMed",
                title="Forest Plot",
                width=600,
                height=625,
                renderFun=".plot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotLarge",
                title="Forest Plot",
                width=600,
                height=900,
                renderFun=".plot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotSmallWide",
                title="Forest Plot",
                width=900,
                height=450,
                renderFun=".plot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotMedWide",
                title="Forest Plot",
                width=900,
                height=625,
                renderFun=".plot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotLargeWide",
                title="Forest Plot",
                width=900,
                height=900,
                renderFun=".plot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Table$new(
                options=options,
                name="selModelOutput",
                title="Selection Model Results",
                refs=list(
                    "metafor"),
                rows=1,
                columns=list(
                    list(
                        `name`="deltaEstimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="deltaSE", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="deltaPVAL", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pval"),
                    list(
                        `name`="deltaCILB", 
                        `title`="CI Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="deltaCIUB", 
                        `title`="CI Upper Bound", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fsnRICH",
                title="",
                rows=4,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Test Name", 
                        `type`="text"),
                    list(
                        `name`="failSafeNumber", 
                        `title`="value", 
                        `type`="integer", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="funplot",
                title="Funnel Plot",
                width=600,
                height=450,
                renderFun=".funplot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Image$new(
                options=options,
                name="funplotMed",
                title="Funnel Plot",
                width=750,
                height=563,
                renderFun=".funplot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Image$new(
                options=options,
                name="funplotLarge",
                title="Funnel Plot",
                width=900,
                height=675,
                renderFun=".funplot",
                refs=list(
                    "metafor")))
            self$add(jmvcore::Table$new(
                options=options,
                name="resultsTES",
                title="Test of Excess Significance | Significant Findings",
                rows=3,
                refs=list(
                    "tes"),
                columns=list(
                    list(
                        `name`="label", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="tesNumberOutput", 
                        `title`="", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="resultsTES2",
                title="Test of Excess Significance | Estimated Power of Tests",
                rows=1,
                refs=list(
                    "tes"),
                columns=list(
                    list(
                        `name`="tesOutputMin", 
                        `title`="Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="tesOutputQ1", 
                        `title`="Q1", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="tesOutputMed", 
                        `title`="Median", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="tesOutputQ3", 
                        `title`="Q3", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="tesOutputMax", 
                        `title`="Max", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tesOutput3",
                title="Test of Excess Significance | Results"))
            self$add(jmvcore::Table$new(
                options=options,
                name="puniformModelOutput",
                title="Publication bias test p-uniform",
                rows=1,
                columns=list(
                    list(
                        `name`="Lpb", 
                        `title`="Test Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pval", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="puniformModelOutput2",
                title="Effect size estimation p-uniform",
                rows=1,
                columns=list(
                    list(
                        `name`="est", 
                        `title`="Effect Size Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cilb", 
                        `title`="CI Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciub", 
                        `title`="CI upper Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="lzero", 
                        `title`="Z", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pval", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ksig", 
                        `title`="Number of Significant Studies", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="TOSToutput",
                title="Two One-Sided Tests Equivalence Testing",
                refs=list(
                    "TOSTER"),
                rows=1,
                columns=list(
                    list(
                        `name`="TOST_Z1", 
                        `title`="Z-Value Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="TOST_p1", 
                        `title`="P-Value Lower Bound", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="TOST_Z2", 
                        `title`="Z-Value Upper Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="TOST_p2", 
                        `title`="P-Value Upper Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="LL_CI_TOST", 
                        `title`="Lower Limit Confidence Interval TOST", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="UL_CI_TOST", 
                        `title`="Upper Limit Confidence Interval TOST", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="LL_CI_ZTEST", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="UL_CI_ZTEST", 
                        `title`="Z-Value Upper Limit Confidence Interval TOST", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="TOSToutputtext",
                title="Two One-Sided Tests Equivalence Testing: Text Summary"))
            self$add(jmvcore::Image$new(
                options=options,
                name="tostplot",
                title="Equivalence Test Plot",
                width=600,
                height=450,
                renderFun=".tostplot",
                refs=list(
                    "TOSTER")))
            self$add(jmvcore::Image$new(
                options=options,
                name="likelihoodPlot",
                title="Likelihood Plot",
                width=600,
                height=450,
                renderFun=".likelihoodPlot",
                refs=list(
                    "llplot")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    diagplot1 = function() private$.items[["diagplot1"]],
                    diagplot2 = function() private$.items[["diagplot2"]],
                    diagplot3 = function() private$.items[["diagplot3"]],
                    diagplot4 = function() private$.items[["diagplot4"]],
                    diagplot5 = function() private$.items[["diagplot5"]],
                    diagplot6 = function() private$.items[["diagplot6"]],
                    diagplot7 = function() private$.items[["diagplot7"]],
                    diagplot8 = function() private$.items[["diagplot8"]],
                    diagplot9 = function() private$.items[["diagplot9"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="diagPlotAll",
                            title="Outlier and Influential Case Diagnostics")
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot1",
                            title="Externally Standardized Residual",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot2",
                            title="DFFITS Values",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot3",
                            title="Cook's Distances",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot4",
                            title="Covariance Ratios",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot5",
                            title="Leave-one-out Tau Estimates",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot6",
                            title="Leave-one-out (residual) Heterogeneity Test Statistics",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot7",
                            title="Hat Values",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot8",
                            title="Weights",
                            width=750,
                            height=300,
                            renderFun=".influDiagPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="diagplot9",
                            title="Q-Q Plot",
                            width=700,
                            height=700,
                            renderFun=".influDiagPlot9"))}))$new(options=options))}))

metaMeanDiffBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "metaMeanDiffBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'metaMeanDiff',
                version = c(1,0,0),
                options = options,
                results = metaMeanDiffResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mean Differences (n, M, SD)
#'
#' 
#' @param data .
#' @param n1i .
#' @param m1i .
#' @param sd1i .
#' @param n2i .
#' @param m2i .
#' @param sd2i .
#' @param slab .
#' @param moderatorcor .
#' @param methodmetacor .
#' @param cormeasure .
#' @param moderatorType .
#' @param testType .
#' @param level .
#' @param showModelFit .
#' @param addcred .
#' @param addfit .
#' @param showweights .
#' @param steps .
#' @param xAxisTitle .
#' @param forestPlotSize .
#' @param funnelPlotSize .
#' @param pchForest .
#' @param forestOrder .
#' @param fsntype .
#' @param tesAlternative .
#' @param tesAlpha .
#' @param tesH0 .
#' @param showTes .
#' @param puniformSide .
#' @param selModelType .
#' @param yaxis .
#' @param yaxisInv .
#' @param enhanceFunnel .
#' @param lowerTOST .
#' @param upperTOST .
#' @param alphaTOST .
#' @param showTOST .
#' @param showInfPlot .
#' @param showLL .
#' @param showPuniform .
#' @param showSelmodel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableTauSqaured} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelFitRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryOutputText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summaryOutputText2} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotMed} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotLarge} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotSmallWide} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotMedWide} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotLargeWide} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$selModelOutput} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fsnRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$funplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$funplotMed} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$funplotLarge} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$resultsTES} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$resultsTES2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tesOutput3} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$puniformModelOutput} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$puniformModelOutput2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$TOSToutput} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$TOSToutputtext} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$tostplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$likelihoodPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot5} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot6} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot7} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot8} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagPlotAll$diagplot9} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
metaMeanDiff <- function(
    data,
    n1i,
    m1i,
    sd1i,
    n2i,
    m2i,
    sd2i,
    slab,
    moderatorcor,
    methodmetacor = "REML",
    cormeasure = "SMD",
    moderatorType = "NON",
    testType = FALSE,
    level = 95,
    showModelFit = FALSE,
    addcred = FALSE,
    addfit = TRUE,
    showweights = FALSE,
    steps = 5,
    xAxisTitle,
    forestPlotSize = "SMALL",
    funnelPlotSize = "SMALL",
    pchForest = "15",
    forestOrder = "fit",
    fsntype = "Rosenthal",
    tesAlternative = "two.sided",
    tesAlpha = 0.5,
    tesH0 = 0,
    showTes = FALSE,
    puniformSide = "right",
    selModelType = "beta",
    yaxis = "sei",
    yaxisInv = FALSE,
    enhanceFunnel = FALSE,
    lowerTOST = -0.5,
    upperTOST = 0.5,
    alphaTOST = 0.05,
    showTOST = FALSE,
    showInfPlot = FALSE,
    showLL = FALSE,
    showPuniform = FALSE,
    showSelmodel = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('metaMeanDiff requires jmvcore to be installed (restart may be required)')

    if ( ! missing(n1i)) n1i <- jmvcore::resolveQuo(jmvcore::enquo(n1i))
    if ( ! missing(m1i)) m1i <- jmvcore::resolveQuo(jmvcore::enquo(m1i))
    if ( ! missing(sd1i)) sd1i <- jmvcore::resolveQuo(jmvcore::enquo(sd1i))
    if ( ! missing(n2i)) n2i <- jmvcore::resolveQuo(jmvcore::enquo(n2i))
    if ( ! missing(m2i)) m2i <- jmvcore::resolveQuo(jmvcore::enquo(m2i))
    if ( ! missing(sd2i)) sd2i <- jmvcore::resolveQuo(jmvcore::enquo(sd2i))
    if ( ! missing(slab)) slab <- jmvcore::resolveQuo(jmvcore::enquo(slab))
    if ( ! missing(moderatorcor)) moderatorcor <- jmvcore::resolveQuo(jmvcore::enquo(moderatorcor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(n1i), n1i, NULL),
            `if`( ! missing(m1i), m1i, NULL),
            `if`( ! missing(sd1i), sd1i, NULL),
            `if`( ! missing(n2i), n2i, NULL),
            `if`( ! missing(m2i), m2i, NULL),
            `if`( ! missing(sd2i), sd2i, NULL),
            `if`( ! missing(slab), slab, NULL),
            `if`( ! missing(moderatorcor), moderatorcor, NULL))


    options <- metaMeanDiffOptions$new(
        n1i = n1i,
        m1i = m1i,
        sd1i = sd1i,
        n2i = n2i,
        m2i = m2i,
        sd2i = sd2i,
        slab = slab,
        moderatorcor = moderatorcor,
        methodmetacor = methodmetacor,
        cormeasure = cormeasure,
        moderatorType = moderatorType,
        testType = testType,
        level = level,
        showModelFit = showModelFit,
        addcred = addcred,
        addfit = addfit,
        showweights = showweights,
        steps = steps,
        xAxisTitle = xAxisTitle,
        forestPlotSize = forestPlotSize,
        funnelPlotSize = funnelPlotSize,
        pchForest = pchForest,
        forestOrder = forestOrder,
        fsntype = fsntype,
        tesAlternative = tesAlternative,
        tesAlpha = tesAlpha,
        tesH0 = tesH0,
        showTes = showTes,
        puniformSide = puniformSide,
        selModelType = selModelType,
        yaxis = yaxis,
        yaxisInv = yaxisInv,
        enhanceFunnel = enhanceFunnel,
        lowerTOST = lowerTOST,
        upperTOST = upperTOST,
        alphaTOST = alphaTOST,
        showTOST = showTOST,
        showInfPlot = showInfPlot,
        showLL = showLL,
        showPuniform = showPuniform,
        showSelmodel = showSelmodel)

    analysis <- metaMeanDiffClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
