
# This file is automatically generated, you probably don't want to edit this

metaMeanDiffOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "metaMeanDiffOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            n1i = NULL,
            m1i = NULL,
            sd1i = NULL,
            n2i = NULL,
            m2i = NULL,
            sd2i = NULL,
            slab = NULL,
            moderatorcor = NULL,
            includemods = FALSE,
            methodmetacor = "REML",
            cormeasure = "SMD",
            level = 95,
            showModelFit = FALSE,
            addcred = FALSE,
            addfit = TRUE,
            showweights = FALSE,
            xAxisTitle = NULL,
            forestOrder = "fit",
            fsntype = "Rosenthal",
            yaxis = "sei",
            yaxisInv = FALSE,
            enhanceFunnel = FALSE, ...) {

            super$initialize(
                package='MAJOR',
                name='metaMeanDiff',
                requiresData=TRUE,
                ...)

            private$..n1i <- jmvcore::OptionVariable$new(
                "n1i",
                n1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..m1i <- jmvcore::OptionVariable$new(
                "m1i",
                m1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..sd1i <- jmvcore::OptionVariable$new(
                "sd1i",
                sd1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..n2i <- jmvcore::OptionVariable$new(
                "n2i",
                n2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..m2i <- jmvcore::OptionVariable$new(
                "m2i",
                m2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..sd2i <- jmvcore::OptionVariable$new(
                "sd2i",
                sd2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab,
                suggested=list(
                    "nominaltext"))
            private$..moderatorcor <- jmvcore::OptionVariable$new(
                "moderatorcor",
                moderatorcor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..includemods <- jmvcore::OptionBool$new(
                "includemods",
                includemods,
                default=FALSE)
            private$..methodmetacor <- jmvcore::OptionList$new(
                "methodmetacor",
                methodmetacor,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "PM",
                    "FE"),
                default="REML")
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "MD",
                    "SMD",
                    "SMDH",
                    "ROM"),
                default="SMD")
            private$..level <- jmvcore::OptionNumber$new(
                "level",
                level,
                min=50,
                max=99.9,
                default=95)
            private$..showModelFit <- jmvcore::OptionBool$new(
                "showModelFit",
                showModelFit,
                default=FALSE)
            private$..addcred <- jmvcore::OptionBool$new(
                "addcred",
                addcred,
                default=FALSE)
            private$..addfit <- jmvcore::OptionBool$new(
                "addfit",
                addfit,
                default=TRUE)
            private$..showweights <- jmvcore::OptionBool$new(
                "showweights",
                showweights,
                default=FALSE)
            private$..xAxisTitle <- jmvcore::OptionString$new(
                "xAxisTitle",
                xAxisTitle)
            private$..forestOrder <- jmvcore::OptionList$new(
                "forestOrder",
                forestOrder,
                options=list(
                    "obs",
                    "fit",
                    "prec",
                    "resid",
                    "abs.resid"),
                default="fit")
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "sei",
                    "vi",
                    "ni",
                    "sqrtni",
                    "lni"),
                default="sei")
            private$..yaxisInv <- jmvcore::OptionBool$new(
                "yaxisInv",
                yaxisInv,
                default=FALSE)
            private$..enhanceFunnel <- jmvcore::OptionBool$new(
                "enhanceFunnel",
                enhanceFunnel,
                default=FALSE)

            self$.addOption(private$..n1i)
            self$.addOption(private$..m1i)
            self$.addOption(private$..sd1i)
            self$.addOption(private$..n2i)
            self$.addOption(private$..m2i)
            self$.addOption(private$..sd2i)
            self$.addOption(private$..slab)
            self$.addOption(private$..moderatorcor)
            self$.addOption(private$..includemods)
            self$.addOption(private$..methodmetacor)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..level)
            self$.addOption(private$..showModelFit)
            self$.addOption(private$..addcred)
            self$.addOption(private$..addfit)
            self$.addOption(private$..showweights)
            self$.addOption(private$..xAxisTitle)
            self$.addOption(private$..forestOrder)
            self$.addOption(private$..fsntype)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..yaxisInv)
            self$.addOption(private$..enhanceFunnel)
        }),
    active = list(
        n1i = function() private$..n1i$value,
        m1i = function() private$..m1i$value,
        sd1i = function() private$..sd1i$value,
        n2i = function() private$..n2i$value,
        m2i = function() private$..m2i$value,
        sd2i = function() private$..sd2i$value,
        slab = function() private$..slab$value,
        moderatorcor = function() private$..moderatorcor$value,
        includemods = function() private$..includemods$value,
        methodmetacor = function() private$..methodmetacor$value,
        cormeasure = function() private$..cormeasure$value,
        level = function() private$..level$value,
        showModelFit = function() private$..showModelFit$value,
        addcred = function() private$..addcred$value,
        addfit = function() private$..addfit$value,
        showweights = function() private$..showweights$value,
        xAxisTitle = function() private$..xAxisTitle$value,
        forestOrder = function() private$..forestOrder$value,
        fsntype = function() private$..fsntype$value,
        yaxis = function() private$..yaxis$value,
        yaxisInv = function() private$..yaxisInv$value,
        enhanceFunnel = function() private$..enhanceFunnel$value),
    private = list(
        ..n1i = NA,
        ..m1i = NA,
        ..sd1i = NA,
        ..n2i = NA,
        ..m2i = NA,
        ..sd2i = NA,
        ..slab = NA,
        ..moderatorcor = NA,
        ..includemods = NA,
        ..methodmetacor = NA,
        ..cormeasure = NA,
        ..level = NA,
        ..showModelFit = NA,
        ..addcred = NA,
        ..addfit = NA,
        ..showweights = NA,
        ..xAxisTitle = NA,
        ..forestOrder = NA,
        ..fsntype = NA,
        ..yaxis = NA,
        ..yaxisInv = NA,
        ..enhanceFunnel = NA)
)

metaMeanDiffResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$.items[["textRICH"]],
        tableTauSqaured = function() private$.items[["tableTauSqaured"]],
        modelFitRICH = function() private$.items[["modelFitRICH"]],
        plot = function() private$.items[["plot"]],
        pubBias = function() private$.items[["pubBias"]],
        funplot = function() private$.items[["funplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="textRICH",
                title="Random-Effects Model",
                rows=2,
                columns=list(
                    list(
                        `name`="Intercept", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `type`="number"),
                    list(
                        `name`="Z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="CILow", 
                        `title`="CI Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="CIHigh", 
                        `title`="CI Upper Bound", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableTauSqaured",
                title="Heterogeneity Statistics",
                rows=1,
                columns=list(
                    list(
                        `name`="tauSQRT", 
                        `title`="Tau", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="tauSqComb", 
                        `title`="Tau\u00B2", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ISqu", 
                        `title`="I\u00B2", 
                        `type`="text"),
                    list(
                        `name`="HSqu", 
                        `title`="H\u00B2", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="RSqu", 
                        `title`="R\u00B2", 
                        `type`="text"),
                    list(
                        `name`="QallDF", 
                        `title`="df", 
                        `type`="integer", 
                        `format`="zto"),
                    list(
                        `name`="Qall", 
                        `title`="Q", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="QallPval", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelFitRICH",
                title="Model Fit Statistics and Information Criteria",
                rows=2,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="loglikelihood", 
                        `title`="log-likelihood", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="deviance", 
                        `title`="Deviance", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="AIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="BIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="AICc", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    fsnRICH = function() private$.items[["fsnRICH"]],
                    rankRICH = function() private$.items[["rankRICH"]],
                    regRICH = function() private$.items[["regRICH"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pubBias",
                            title="Publication Bias Assessment")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="fsnRICH",
                            title="Fail-Safe N Analysis",
                            rows=1,
                            columns=list(
                                list(
                                    `name`="failSafeNumber", 
                                    `title`="Fail-safe N", 
                                    `type`="integer", 
                                    `format`="zto"),
                                list(
                                    `name`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="rankRICH",
                            title="Rank Correlation Test for Funnel Plot Asymmetry",
                            rows=1,
                            columns=list(
                                list(
                                    `name`="rankTau", 
                                    `title`="Kendall's Tau", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="regRICH",
                            title="Regression Test for Funnel Plot Asymmetry",
                            rows=1,
                            columns=list(
                                list(
                                    `name`="Z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="funplot",
                title="Funnel Plot",
                width=600,
                height=450,
                renderFun=".funplot"))}))

metaMeanDiffBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "metaMeanDiffBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'metaMeanDiff',
                version = c(1,0,0),
                options = options,
                results = metaMeanDiffResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Mean Differences (n, M, SD)
#'
#' 
#' @param data .
#' @param n1i .
#' @param m1i .
#' @param sd1i .
#' @param n2i .
#' @param m2i .
#' @param sd2i .
#' @param slab .
#' @param moderatorcor .
#' @param includemods .
#' @param methodmetacor .
#' @param cormeasure .
#' @param level .
#' @param showModelFit .
#' @param addcred .
#' @param addfit .
#' @param showweights .
#' @param xAxisTitle .
#' @param forestOrder .
#' @param fsntype .
#' @param yaxis .
#' @param yaxisInv .
#' @param enhanceFunnel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableTauSqaured} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelFitRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$pubBias$fsnRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pubBias$rankRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pubBias$regRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$funplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
metaMeanDiff <- function(
    data,
    n1i,
    m1i,
    sd1i,
    n2i,
    m2i,
    sd2i,
    slab,
    moderatorcor,
    includemods = FALSE,
    methodmetacor = "REML",
    cormeasure = "SMD",
    level = 95,
    showModelFit = FALSE,
    addcred = FALSE,
    addfit = TRUE,
    showweights = FALSE,
    xAxisTitle,
    forestOrder = "fit",
    fsntype = "Rosenthal",
    yaxis = "sei",
    yaxisInv = FALSE,
    enhanceFunnel = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('metaMeanDiff requires jmvcore to be installed (restart may be required)')

    options <- metaMeanDiffOptions$new(
        n1i = n1i,
        m1i = m1i,
        sd1i = sd1i,
        n2i = n2i,
        m2i = m2i,
        sd2i = sd2i,
        slab = slab,
        moderatorcor = moderatorcor,
        includemods = includemods,
        methodmetacor = methodmetacor,
        cormeasure = cormeasure,
        level = level,
        showModelFit = showModelFit,
        addcred = addcred,
        addfit = addfit,
        showweights = showweights,
        xAxisTitle = xAxisTitle,
        forestOrder = forestOrder,
        fsntype = fsntype,
        yaxis = yaxis,
        yaxisInv = yaxisInv,
        enhanceFunnel = enhanceFunnel)

    results <- metaMeanDiffResults$new(
        options = options)

    analysis <- metaMeanDiffClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
