
# This file is automatically generated, you probably don't want to edit this

multiLevelMetaAnalysisOddsRatiosOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multiLevelMetaAnalysisOddsRatiosOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ai = NULL,
            bi = NULL,
            ci = NULL,
            di = NULL,
            studyNum = NULL, ...) {

            super$initialize(
                package='MAJOR',
                name='multiLevelMetaAnalysisOddsRatios',
                requiresData=TRUE,
                ...)

            private$..ai <- jmvcore::OptionVariable$new(
                "ai",
                ai,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..bi <- jmvcore::OptionVariable$new(
                "bi",
                bi,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ci <- jmvcore::OptionVariable$new(
                "ci",
                ci,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..di <- jmvcore::OptionVariable$new(
                "di",
                di,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..studyNum <- jmvcore::OptionVariable$new(
                "studyNum",
                studyNum,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))

            self$.addOption(private$..ai)
            self$.addOption(private$..bi)
            self$.addOption(private$..ci)
            self$.addOption(private$..di)
            self$.addOption(private$..studyNum)
        }),
    active = list(
        ai = function() private$..ai$value,
        bi = function() private$..bi$value,
        ci = function() private$..ci$value,
        di = function() private$..di$value,
        studyNum = function() private$..studyNum$value),
    private = list(
        ..ai = NA,
        ..bi = NA,
        ..ci = NA,
        ..di = NA,
        ..studyNum = NA)
)

multiLevelMetaAnalysisOddsRatiosResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        resultsTable = function() private$.items[["resultsTable"]],
        data1 = function() private$.items[["data1"]],
        data1a = function() private$.items[["data1a"]],
        data2 = function() private$.items[["data2"]],
        data2a = function() private$.items[["data2a"]],
        data3 = function() private$.items[["data3"]],
        options = function() private$.items[["options"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dichotomous Models")
            self$add(jmvcore::Table$new(
                options=options,
                name="resultsTable",
                refs=list(
                    "metafor"),
                title="Random-Effects Model",
                rows=2,
                columns=list(
                    list(
                        `name`="Intercept", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `type`="number"),
                    list(
                        `name`="Z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="CILow", 
                        `title`="CI Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="CIHigh", 
                        `title`="CI Upper Bound", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="data1",
                title="data1"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="data1a",
                title="data1a"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="data2",
                title="data2"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="data2a",
                title="data2a"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="data3",
                title="data3"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="options",
                title="options"))}))

multiLevelMetaAnalysisOddsRatiosBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multiLevelMetaAnalysisOddsRatiosBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'multiLevelMetaAnalysisOddsRatios',
                version = c(1,0,0),
                options = options,
                results = multiLevelMetaAnalysisOddsRatiosResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Dichotomous Models
#'
#' 
#' @param data .
#' @param ai .
#' @param bi .
#' @param ci .
#' @param di .
#' @param studyNum .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$resultsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$data1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$data1a} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$data2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$data2a} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$data3} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$options} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$resultsTable$asDF}
#'
#' \code{as.data.frame(results$resultsTable)}
#'
#' @export
multiLevelMetaAnalysisOddsRatios <- function(
    data,
    ai,
    bi,
    ci,
    di,
    studyNum) {

    if ( ! requireNamespace('jmvcore'))
        stop('multiLevelMetaAnalysisOddsRatios requires jmvcore to be installed (restart may be required)')

    if ( ! missing(ai)) ai <- jmvcore::resolveQuo(jmvcore::enquo(ai))
    if ( ! missing(bi)) bi <- jmvcore::resolveQuo(jmvcore::enquo(bi))
    if ( ! missing(ci)) ci <- jmvcore::resolveQuo(jmvcore::enquo(ci))
    if ( ! missing(di)) di <- jmvcore::resolveQuo(jmvcore::enquo(di))
    if ( ! missing(studyNum)) studyNum <- jmvcore::resolveQuo(jmvcore::enquo(studyNum))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ai), ai, NULL),
            `if`( ! missing(bi), bi, NULL),
            `if`( ! missing(ci), ci, NULL),
            `if`( ! missing(di), di, NULL),
            `if`( ! missing(studyNum), studyNum, NULL))


    options <- multiLevelMetaAnalysisOddsRatiosOptions$new(
        ai = ai,
        bi = bi,
        ci = ci,
        di = di,
        studyNum = studyNum)

    analysis <- multiLevelMetaAnalysisOddsRatiosClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
