
# This file is automatically generated, you probably don't want to edit this

multiLevelMetaMeanDiffOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multiLevelMetaMeanDiffOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            n1i = NULL,
            m1i = NULL,
            sd1i = NULL,
            n2i = NULL,
            m2i = NULL,
            sd2i = NULL,
            clusterOne = NULL,
            clusterTwo = NULL,
            slab = NULL,
            methodmetacor = "REML",
            cormeasure = "SMD",
            showModelFit = FALSE, ...) {

            super$initialize(
                package='MAJOR',
                name='multiLevelMetaMeanDiff',
                requiresData=TRUE,
                ...)

            private$..n1i <- jmvcore::OptionVariable$new(
                "n1i",
                n1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m1i <- jmvcore::OptionVariable$new(
                "m1i",
                m1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd1i <- jmvcore::OptionVariable$new(
                "sd1i",
                sd1i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..n2i <- jmvcore::OptionVariable$new(
                "n2i",
                n2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..m2i <- jmvcore::OptionVariable$new(
                "m2i",
                m2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sd2i <- jmvcore::OptionVariable$new(
                "sd2i",
                sd2i,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..clusterOne <- jmvcore::OptionVariable$new(
                "clusterOne",
                clusterOne,
                permitted=list(
                    "numeric"))
            private$..clusterTwo <- jmvcore::OptionVariable$new(
                "clusterTwo",
                clusterTwo,
                permitted=list(
                    "numeric"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab,
                suggested=list(
                    "nominal"))
            private$..methodmetacor <- jmvcore::OptionList$new(
                "methodmetacor",
                methodmetacor,
                options=list(
                    "ML",
                    "REML",
                    "FE"),
                default="REML")
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "MD",
                    "SMD",
                    "SMDH",
                    "ROM"),
                default="SMD")
            private$..showModelFit <- jmvcore::OptionBool$new(
                "showModelFit",
                showModelFit,
                default=FALSE)

            self$.addOption(private$..n1i)
            self$.addOption(private$..m1i)
            self$.addOption(private$..sd1i)
            self$.addOption(private$..n2i)
            self$.addOption(private$..m2i)
            self$.addOption(private$..sd2i)
            self$.addOption(private$..clusterOne)
            self$.addOption(private$..clusterTwo)
            self$.addOption(private$..slab)
            self$.addOption(private$..methodmetacor)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..showModelFit)
        }),
    active = list(
        n1i = function() private$..n1i$value,
        m1i = function() private$..m1i$value,
        sd1i = function() private$..sd1i$value,
        n2i = function() private$..n2i$value,
        m2i = function() private$..m2i$value,
        sd2i = function() private$..sd2i$value,
        clusterOne = function() private$..clusterOne$value,
        clusterTwo = function() private$..clusterTwo$value,
        slab = function() private$..slab$value,
        methodmetacor = function() private$..methodmetacor$value,
        cormeasure = function() private$..cormeasure$value,
        showModelFit = function() private$..showModelFit$value),
    private = list(
        ..n1i = NA,
        ..m1i = NA,
        ..sd1i = NA,
        ..n2i = NA,
        ..m2i = NA,
        ..sd2i = NA,
        ..clusterOne = NA,
        ..clusterTwo = NA,
        ..slab = NA,
        ..methodmetacor = NA,
        ..cormeasure = NA,
        ..showModelFit = NA)
)

multiLevelMetaMeanDiffResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$.items[["textRICH"]],
        modelFitRICH = function() private$.items[["modelFitRICH"]],
        tableVariance = function() private$.items[["tableVariance"]],
        tableHeterogeneity = function() private$.items[["tableHeterogeneity"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mean Differences")
            self$add(jmvcore::Table$new(
                options=options,
                name="textRICH",
                refs=list(
                    "metafor"),
                title="Multilevel Model",
                rows=1,
                columns=list(
                    list(
                        `name`="Intercept", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `type`="number"),
                    list(
                        `name`="Z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="CILow", 
                        `title`="CI Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="CIHigh", 
                        `title`="CI Upper Bound", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelFitRICH",
                title="Model Fit Statistics and Information Criteria",
                rows=2,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="loglikelihood", 
                        `title`="log-likelihood", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="deviance", 
                        `title`="Deviance", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="AIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="BIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="AICc", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableVariance",
                title="Variance Components",
                rows=2,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="integer", 
                        `format`="zto"),
                    list(
                        `name`="squareroot", 
                        `title`="Square Root", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="numLevel", 
                        `title`="Number of Levels", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableHeterogeneity",
                title="Heterogeneity Statistics",
                rows=1,
                columns=list(
                    list(
                        `name`="QallDF", 
                        `title`="df", 
                        `type`="integer", 
                        `format`="zto"),
                    list(
                        `name`="Qall", 
                        `title`="Q", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="QallPval", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

multiLevelMetaMeanDiffBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multiLevelMetaMeanDiffBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'multiLevelMetaMeanDiff',
                version = c(1,0,0),
                options = options,
                results = multiLevelMetaMeanDiffResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Mean Differences
#'
#' 
#' @param data .
#' @param n1i .
#' @param m1i .
#' @param sd1i .
#' @param n2i .
#' @param m2i .
#' @param sd2i .
#' @param clusterOne .
#' @param clusterTwo .
#' @param slab .
#' @param methodmetacor .
#' @param cormeasure .
#' @param showModelFit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelFitRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableVariance} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableHeterogeneity} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
multiLevelMetaMeanDiff <- function(
    data,
    n1i,
    m1i,
    sd1i,
    n2i,
    m2i,
    sd2i,
    clusterOne,
    clusterTwo,
    slab,
    methodmetacor = "REML",
    cormeasure = "SMD",
    showModelFit = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('multiLevelMetaMeanDiff requires jmvcore to be installed (restart may be required)')

    if ( ! missing(n1i)) n1i <- jmvcore::resolveQuo(jmvcore::enquo(n1i))
    if ( ! missing(m1i)) m1i <- jmvcore::resolveQuo(jmvcore::enquo(m1i))
    if ( ! missing(sd1i)) sd1i <- jmvcore::resolveQuo(jmvcore::enquo(sd1i))
    if ( ! missing(n2i)) n2i <- jmvcore::resolveQuo(jmvcore::enquo(n2i))
    if ( ! missing(m2i)) m2i <- jmvcore::resolveQuo(jmvcore::enquo(m2i))
    if ( ! missing(sd2i)) sd2i <- jmvcore::resolveQuo(jmvcore::enquo(sd2i))
    if ( ! missing(clusterOne)) clusterOne <- jmvcore::resolveQuo(jmvcore::enquo(clusterOne))
    if ( ! missing(clusterTwo)) clusterTwo <- jmvcore::resolveQuo(jmvcore::enquo(clusterTwo))
    if ( ! missing(slab)) slab <- jmvcore::resolveQuo(jmvcore::enquo(slab))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(n1i), n1i, NULL),
            `if`( ! missing(m1i), m1i, NULL),
            `if`( ! missing(sd1i), sd1i, NULL),
            `if`( ! missing(n2i), n2i, NULL),
            `if`( ! missing(m2i), m2i, NULL),
            `if`( ! missing(sd2i), sd2i, NULL),
            `if`( ! missing(clusterOne), clusterOne, NULL),
            `if`( ! missing(clusterTwo), clusterTwo, NULL),
            `if`( ! missing(slab), slab, NULL))


    options <- multiLevelMetaMeanDiffOptions$new(
        n1i = n1i,
        m1i = m1i,
        sd1i = sd1i,
        n2i = n2i,
        m2i = m2i,
        sd2i = sd2i,
        clusterOne = clusterOne,
        clusterTwo = clusterTwo,
        slab = slab,
        methodmetacor = methodmetacor,
        cormeasure = cormeasure,
        showModelFit = showModelFit)

    analysis <- multiLevelMetaMeanDiffClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
