
# This file is automatically generated, you probably don't want to edit this

robvisOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "robvisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            D1 = NULL,
            D2 = NULL,
            D3 = NULL,
            D4 = NULL,
            D5 = NULL,
            Overall = NULL,
            Weight = NULL,
            Study = NULL,
            alt = "notequal",
            varEq = TRUE, ...) {

            super$initialize(
                package='MAJOR',
                name='robvis',
                requiresData=TRUE,
                ...)

            private$..D1 <- jmvcore::OptionVariable$new(
                "D1",
                D1,
                suggested=list(
                    "nominal"))
            private$..D2 <- jmvcore::OptionVariable$new(
                "D2",
                D2,
                suggested=list(
                    "nominal"))
            private$..D3 <- jmvcore::OptionVariable$new(
                "D3",
                D3,
                suggested=list(
                    "nominal"))
            private$..D4 <- jmvcore::OptionVariable$new(
                "D4",
                D4,
                suggested=list(
                    "nominal"))
            private$..D5 <- jmvcore::OptionVariable$new(
                "D5",
                D5,
                suggested=list(
                    "nominal"))
            private$..Overall <- jmvcore::OptionVariable$new(
                "Overall",
                Overall,
                suggested=list(
                    "nominal"))
            private$..Weight <- jmvcore::OptionVariable$new(
                "Weight",
                Weight,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..Study <- jmvcore::OptionVariable$new(
                "Study",
                Study,
                suggested=list(
                    "nominal"))
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "notequal",
                    "onegreater",
                    "twogreater"),
                default="notequal")
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)

            self$.addOption(private$..D1)
            self$.addOption(private$..D2)
            self$.addOption(private$..D3)
            self$.addOption(private$..D4)
            self$.addOption(private$..D5)
            self$.addOption(private$..Overall)
            self$.addOption(private$..Weight)
            self$.addOption(private$..Study)
            self$.addOption(private$..alt)
            self$.addOption(private$..varEq)
        }),
    active = list(
        D1 = function() private$..D1$value,
        D2 = function() private$..D2$value,
        D3 = function() private$..D3$value,
        D4 = function() private$..D4$value,
        D5 = function() private$..D5$value,
        Overall = function() private$..Overall$value,
        Weight = function() private$..Weight$value,
        Study = function() private$..Study$value,
        alt = function() private$..alt$value,
        varEq = function() private$..varEq$value),
    private = list(
        ..D1 = NA,
        ..D2 = NA,
        ..D3 = NA,
        ..D4 = NA,
        ..D5 = NA,
        ..Overall = NA,
        ..Weight = NA,
        ..Study = NA,
        ..alt = NA,
        ..varEq = NA)
)

robvisResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Risk of Bias Assessment")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Barplot of Risk-of-Bias Assessment",
                width=750,
                height=450,
                renderFun=".plot"))}))

robvisBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "robvisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MAJOR',
                name = 'robvis',
                version = c(1,0,0),
                options = options,
                results = robvisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Risk of Bias Assessment
#'
#' 
#' @param data .
#' @param D1 .
#' @param D2 .
#' @param D3 .
#' @param D4 .
#' @param D5 .
#' @param Overall .
#' @param Weight .
#' @param Study .
#' @param alt .
#' @param varEq .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
robvis <- function(
    data,
    D1,
    D2,
    D3,
    D4,
    D5,
    Overall,
    Weight,
    Study,
    alt = "notequal",
    varEq = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('robvis requires jmvcore to be installed (restart may be required)')

    if ( ! missing(D1)) D1 <- jmvcore::resolveQuo(jmvcore::enquo(D1))
    if ( ! missing(D2)) D2 <- jmvcore::resolveQuo(jmvcore::enquo(D2))
    if ( ! missing(D3)) D3 <- jmvcore::resolveQuo(jmvcore::enquo(D3))
    if ( ! missing(D4)) D4 <- jmvcore::resolveQuo(jmvcore::enquo(D4))
    if ( ! missing(D5)) D5 <- jmvcore::resolveQuo(jmvcore::enquo(D5))
    if ( ! missing(Overall)) Overall <- jmvcore::resolveQuo(jmvcore::enquo(Overall))
    if ( ! missing(Weight)) Weight <- jmvcore::resolveQuo(jmvcore::enquo(Weight))
    if ( ! missing(Study)) Study <- jmvcore::resolveQuo(jmvcore::enquo(Study))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(D1), D1, NULL),
            `if`( ! missing(D2), D2, NULL),
            `if`( ! missing(D3), D3, NULL),
            `if`( ! missing(D4), D4, NULL),
            `if`( ! missing(D5), D5, NULL),
            `if`( ! missing(Overall), Overall, NULL),
            `if`( ! missing(Weight), Weight, NULL),
            `if`( ! missing(Study), Study, NULL))


    options <- robvisOptions$new(
        D1 = D1,
        D2 = D2,
        D3 = D3,
        D4 = D4,
        D5 = D5,
        Overall = Overall,
        Weight = Weight,
        Study = Study,
        alt = alt,
        varEq = varEq)

    analysis <- robvisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
